import Foundation

// On-disk index of every Claude Code session we can see under
// ~/.claude/projects/. Per-session aggregates: which folder it ran
// in, the autogenerated chat title, the latest model, token counts
// broken out by billing class, and the last-activity timestamp.
//
// The indexer is meant to be cheap on warm runs: it stats every
// .jsonl, skips files whose (mtime, size) matches the cached entry,
// and only re-parses the line stream of changed files.

nonisolated struct ModelPricing: Sendable {
    let input: Double   // USD per 1M tokens
    let output: Double
    var cacheWrite: Double { input * 1.25 }
    var cacheRead: Double { input * 0.1 }
}

nonisolated enum SessionProvider: String, Codable, Sendable {
    case claude
    case codex
    // Claude Code running inside the Claude desktop app ("local agent
    // mode" / cowork) — a separate sandbox under ~/Library/Application
    // Support/Claude, not ~/.claude.
    case claudeDesktop
}

nonisolated struct SessionIndexEntry: Codable, Equatable, Sendable {
    let sessionId: String
    // var (not let) so a Codex stub can have its cwd filled in by
    // deepScan once session_meta is parsed.
    var cwd: String
    var provider: SessionProvider = .claude
    // `title` is the auto-generated description (Claude's ai-title /
    // Codex's first user prompt). `name` is the user-given label set
    // via /rename in Claude Code (custom-title record).
    var title: String?
    var name: String?
    var model: String?
    // Reasoning-effort knob for Codex sessions ("low" / "medium" /
    // "high" / "xhigh"). nil for Claude or when the rollout doesn't
    // record one. Displayed appended to the model name with a space.
    var effort: String?
    // Surface a Claude session was driven from: "cli" (terminal) or
    // "claude-desktop" (the Claude app's Code tab). nil for Codex / unknown.
    // Same ~/.claude storage either way — this is the only distinguisher.
    var entrypoint: String?
    // True when this session is running in / belongs to the Claude desktop
    // app (its Code tab, or the local-agent-mode/Cowork sandbox).
    var isClaudeDesktop: Bool { provider == .claudeDesktop || entrypoint == "claude-desktop" }
    // Tokens broken out by what they bill as. cacheCreation costs
    // 1.25× input price; cacheRead costs 0.1× input price; the
    // others are 1× input / 5× input (output) respectively. Summing
    // them with model pricing gives the rough $ spent on the
    // session (assuming the latest seen model is representative,
    // which is true for the common cli case).
    var inputTokens: Int64 = 0
    var cacheCreationTokens: Int64 = 0
    var cacheReadTokens: Int64 = 0
    var outputTokens: Int64 = 0
    // Count of "actual" typed user messages — excludes records that
    // are just tool_result echoes from the system.
    var userMessageCount: Int = 0
    // Number of model responses (agentic steps) in the session — distinct
    // from userMessageCount, which counts human turns. Claude: distinct
    // assistant requestIds; Codex: token_count events (one per response).
    // A tool-looping turn produces many of these per single user message.
    var turns: Int = 0
    // Lines of code the session's Edit/Write tools touched, counted
    // from structuredPatch hunks (+/- prefixes) and created-file
    // contents. Tool-write churn, not a net git diff: rewriting the
    // same spot three times counts three times. Codex rollouts don't
    // carry this — they stay at 0.
    var linesAdded: Int64 = 0
    var linesRemoved: Int64 = 0
    // gitBranch from the last assistant record we saw in the jsonl —
    // approximates what branch the session was last working on.
    var lastGitBranch: String?
    var lastActivity: Date
    var startedAt: Date?
    // Cached so we can skip re-parsing on a stat()-only check next
    // time round.
    var fileSize: Int64
    // How many bytes of the jsonl we've parsed token-usage for. When
    // the file grows, deepScan can read only the delta starting here
    // and add to the existing token / branch counters instead of
    // re-parsing the whole megabyte stream.
    var lastParsedSize: Int64 = 0
    // Compact tool-activity summary (top tools / bash verbs / repeated files),
    // computed once at index time so reports read it here instead of re-parsing
    // the transcript. nil until the first deep scan.
    var toolSummary: String?

    var folderName: String { URL(fileURLWithPath: cwd).lastPathComponent }
    var displayTitle: String {
        let t = title?.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines) ?? ""
        return t.isEmpty ? folderName : t
    }
    var relativePath: String {
        let home = NSHomeDirectory()
        if cwd.hasPrefix(home + "/") {
            return "~" + cwd.dropFirst(home.count)
        }
        if cwd == home { return "~" }
        return cwd
    }

    // Claude spawns sub-task sessions under /private/tmp/claude/<uid>/
    // and the SDK keeps its scratch state under /private/var/folders/.
    // Neither is something the user opened by hand — hide them by
    // default in the main window.
    var isTemporary: Bool {
        cwd.hasPrefix("/private/tmp/") || cwd.hasPrefix("/private/var/")
    }

    var pricing: ModelPricing { SessionIndex.pricing(for: model) }

    var costUSD: Double {
        let p = pricing
        return (Double(inputTokens) * p.input
            + Double(cacheCreationTokens) * p.cacheWrite
            + Double(cacheReadTokens) * p.cacheRead
            + Double(outputTokens) * p.output) / 1_000_000
    }
}

nonisolated struct SessionIndex: Codable, Sendable {
    // Bump when SessionIndexEntry changes shape so we discard caches
    // built by older EpiScope versions instead of decoding them with
    // zero-filled new fields.
    static let currentVersion = 13

    var version: Int = SessionIndex.currentVersion
    var entries: [SessionIndexEntry] = []

    // Hardcoded prices — refresh when Anthropic moves their pricing
    // page. Unknown models fall back to Sonnet (the middle tier).
    // Opus 4.x is priced $5/$25 per 1M (verified against Claude Code's
    // own /usage display, not the legacy Opus 3 $15/$75 rates). Sonnet
    // / Haiku rates checked against the haiku line in the same output.
    // Fable 5 (released 2026-06-09) is the new flagship at double Opus.
    static let pricingTable: [String: ModelPricing] = [
        "claude-fable-5":    ModelPricing(input: 10, output: 50),
        "claude-mythos-5":   ModelPricing(input: 10, output: 50),
        "claude-opus-4-8":   ModelPricing(input: 5,  output: 25),
        "claude-opus-4-7":   ModelPricing(input: 5,  output: 25),
        "claude-opus-4-6":   ModelPricing(input: 5,  output: 25),
        "claude-opus-4-5":   ModelPricing(input: 5,  output: 25),
        "claude-sonnet-4-6": ModelPricing(input: 3,  output: 15),
        "claude-sonnet-4-5": ModelPricing(input: 3,  output: 15),
        "claude-haiku-4-5":  ModelPricing(input: 1,  output: 5),
        // OpenAI / Codex. Cached input lands in cacheRead bucket
        // (12.5% of input price); no explicit cache-write tier.
        "openai-gpt-5":          ModelPricing(input: 5,    output: 10),
        "openai-gpt-5-codex":    ModelPricing(input: 5,    output: 10),
        "openai-gpt-5-mini":     ModelPricing(input: 0.25, output: 2),
        "openai-gpt-5-nano":     ModelPricing(input: 0.05, output: 0.4),
    ]
    static let defaultPricing = ModelPricing(input: 3, output: 15)

    static func pricing(for model: String?) -> ModelPricing {
        guard let m = model else { return defaultPricing }
        return pricingTable[m] ?? defaultPricing
    }
}

@MainActor
final class SessionIndexer {
    private(set) var entries: [SessionIndexEntry] = []
    var onUpdate: (() -> Void)?
    // Fired alongside onUpdate with the current entries — the search index
    // reconciles its per-session FTS rows off this (cheap when nothing grew,
    // so it's safe to fire on every entries change). Kept separate from
    // onUpdate, which MainWindowController owns for the table.
    var onEntriesUpdated: (([SessionIndexEntry]) -> Void)?
    // Number of sessions still being deep-scanned. 0 means idle / done.
    // MainWindow polls this to render the "Loading X / Y" indicator.
    private(set) var pendingDeepScan: Int = 0
    private(set) var totalDeepScan: Int = 0
    var onProgress: (() -> Void)?

    nonisolated private static let workQueue = DispatchQueue(label: "episcope.session-indexer", qos: .utility)
    // Per-project-dir memo for the shallow walk. The decoded cwd + temp flag
    // is a pure function of the (stable) directory name; the jsonl listing is
    // reused until the directory's mtime changes. Both are only ever touched
    // from rebuildShallow on the serial workQueue, so no locking is needed.
    nonisolated(unsafe) private static var cwdDecodeCache: [String: (cwd: String, isTemp: Bool)] = [:]
    nonisolated(unsafe) private static var dirListCache: [String: (mtime: Date, jsonls: [URL])] = [:]
    nonisolated private static let projectsDir: URL = FileManager.default
        .homeDirectoryForCurrentUser
        .appending(path: ".claude/projects", directoryHint: .isDirectory)

    nonisolated private static let codexSessionsDir: URL = FileManager.default
        .homeDirectoryForCurrentUser
        .appending(path: ".codex/sessions", directoryHint: .isDirectory)

    // Claude desktop ("local agent mode") sessions live two levels deep:
    // <root>/<account>/<workspace>/local_<uuid>.json (metadata) alongside
    // local_<uuid>/audit.jsonl (the transcript).
    nonisolated private static let claudeDesktopRoot: URL = FileManager.default
        .homeDirectoryForCurrentUser
        .appending(path: "Library/Application Support/Claude/local-agent-mode-sessions",
                   directoryHint: .isDirectory)

    nonisolated private static let indexURL: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let dir = base.appending(path: "EpiScope", directoryHint: .isDirectory)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appending(path: "sessions.json")
    }()

    private var timer: Timer?
    // FSEvents doorbell: set when the watched transcript trees change, so the
    // 1 s heartbeat can skip its file walk entirely when nothing moved.
    // Starts true for the initial scan; a safety-net forces a scan periodically
    // in case an event is ever missed.
    private var watcher: DirWatcher?
    private var projectsDirty = true
    private var ticksSinceScan = 0
    private static let safetyScanTicks = 30   // ~30 s
    private var reindexing = false
    // True while the main window is closed / miniaturized — nobody is
    // looking at the table, so the 2-second sweep is pure waste. The
    // menu bar runs off SessionMonitor and doesn't need the index.
    private var paused = false
    // Disk-save debounce: the index is rewritten at most once per
    // saveInterval while sessions are active, plus a forced flush on
    // pause / app termination.
    private var indexDirty = false
    private var lastIndexSave = Date.distantPast
    private static let saveInterval: TimeInterval = 30

    func start() {
        loadFromDisk()
        if !entries.isEmpty { publish() }
        startWatcher()
        kickReindex()
        startTimer()
    }

    private func startWatcher() {
        let paths = [Self.projectsDir.path, Self.codexSessionsDir.path, Self.claudeDesktopRoot.path]
        watcher = DirWatcher(paths: paths) { [weak self] in
            DispatchQueue.main.async { self?.projectsDirty = true }
        }
    }

    func pause() {
        paused = true
        timer?.invalidate()
        timer = nil
        flushIndexToDisk()
    }

    func resume() {
        paused = false
        if timer == nil { startTimer() }
        kickReindex()
    }

    private func startTimer() {
        // 1 s heartbeat, but it only does work when FSEvents says the transcript
        // trees actually changed (projectsDirty). On a dirty tick it stats the
        // jsonls and incrementally deep-scans just the files that grew (their
        // appended tail). Idle ticks cost nothing. A safety-net forces a scan
        // every safetyScanTicks in case an event is missed.
        let t = Timer(timeInterval: 1, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.heartbeat() }
        }
        t.tolerance = 0.3
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    private func heartbeat() {
        ticksSinceScan += 1
        guard projectsDirty || ticksSinceScan >= Self.safetyScanTicks else { return }
        projectsDirty = false
        ticksSinceScan = 0
        kickReindex()
    }

    func flushIndexToDisk() {
        maybeSaveIndex(force: true)
    }

    private func maybeSaveIndex(force: Bool = false) {
        guard indexDirty else { return }
        guard force || Date().timeIntervalSince(lastIndexSave) >= Self.saveInterval else { return }
        indexDirty = false
        lastIndexSave = Date()
        let snapshot = SessionIndex(entries: entries)
        Self.workQueue.async { Self.saveToDisk(snapshot) }
    }

    // Publish an entries change to both consumers: the main-window table
    // (onUpdate) and the search indexer (onEntriesUpdated).
    private func publish() {
        onUpdate?()
        onEntriesUpdated?(entries)
    }

    func kickReindex() {
        guard !paused, !reindexing else { return }
        reindexing = true
        let cached = entries
        Self.workQueue.async {
            // Phase 1 — cheap shallow pass. Returns one entry per
            // jsonl on disk: cache hits are full entries, misses are
            // stubs with only filesystem metadata populated.
            let (allEntries, stubIds, codexPaths) = Self.rebuildShallow(cache: cached)
            DispatchQueue.main.async { [weak self] in
                guard let self else { return }
                if allEntries != self.entries {
                    self.entries = allEntries
                    self.publish()
                }
                self.totalDeepScan = stubIds.count
                self.pendingDeepScan = stubIds.count
                self.onProgress?()
            }
            guard !stubIds.isEmpty else {
                DispatchQueue.main.async { [weak self] in
                    self?.reindexing = false
                }
                return
            }
            // Phase 2 — deep-scan only the stubs. Flush a snapshot to
            // the main thread every CHUNK files so the UI ticks.
            let chunk = 12
            var current = allEntries
            var since = 0
            for (idx, entry) in current.enumerated() where stubIds.contains(entry.sessionId) {
                // Per-file pool: deepScan reads + JSON-decodes a whole
                // transcript; without draining here, the autoreleased Foundation
                // temporaries from every file pile up until the batch ends and
                // balloon memory on a cold (re)index.
                autoreleasepool {
                    if let detailed = Self.deepScan(entry: entry, fileURL: codexPaths[entry.sessionId]) {
                        current[idx] = detailed
                    }
                }
                since += 1
                if since >= chunk {
                    let snapshot = current
                    let remaining = stubIds.count - (idx + 1)
                    DispatchQueue.main.async { [weak self] in
                        guard let self else { return }
                        self.entries = snapshot
                        self.pendingDeepScan = max(0, remaining)
                        self.onProgress?()
                        self.publish()
                    }
                    since = 0
                }
            }
            let final = current
            DispatchQueue.main.async { [weak self] in
                guard let self else { return }
                self.entries = final
                self.pendingDeepScan = 0
                self.totalDeepScan = 0
                self.reindexing = false
                self.indexDirty = true
                self.maybeSaveIndex()
                self.onProgress?()
                self.publish()
            }
        }
    }

    // Reindex button: re-read every transcript from byte 0 (ignore the
    // incremental cursors) and publish atomically when done — no flash to
    // stubs, the table keeps its current data until the fresh scan lands.
    // The 1 s sweep handles normal freshness; this is the "rebuild from
    // scratch" escape hatch.
    func fullReindex() {
        guard !paused, !reindexing else { return }
        reindexing = true
        Self.workQueue.async {
            // Empty cache → every file is a fresh stub → deep-scanned in full.
            let (stubs, stubIds, codexPaths) = Self.rebuildShallow(cache: [])
            DispatchQueue.main.async { [weak self] in
                self?.totalDeepScan = stubIds.count
                self?.pendingDeepScan = stubIds.count
                self?.onProgress?()
            }
            var current = stubs
            for (idx, entry) in current.enumerated() where stubIds.contains(entry.sessionId) {
                autoreleasepool {
                    if let detailed = Self.deepScan(entry: entry, fileURL: codexPaths[entry.sessionId]) {
                        current[idx] = detailed
                    }
                }
            }
            let final = current
            DispatchQueue.main.async { [weak self] in
                guard let self else { return }
                self.entries = final
                self.pendingDeepScan = 0
                self.totalDeepScan = 0
                self.reindexing = false
                self.indexDirty = true
                self.maybeSaveIndex()
                self.onProgress?()
                self.publish()
            }
        }
    }

    // MARK: - On-disk cache

    private func loadFromDisk() {
        let dec = JSONDecoder()
        // Must mirror saveToDisk's encoding strategy — the default
        // (.deferredToDate) would misread the stored milliseconds as
        // seconds-since-2001, every cached mtime would mismatch, and
        // each launch would deep-scan everything from scratch.
        dec.dateDecodingStrategy = .millisecondsSince1970
        guard let data = try? Data(contentsOf: Self.indexURL),
              let idx = try? dec.decode(SessionIndex.self, from: data),
              idx.version == SessionIndex.currentVersion else { return }
        entries = idx.entries
    }

    nonisolated private static func saveToDisk(_ idx: SessionIndex) {
        let enc = JSONEncoder()
        enc.dateEncodingStrategy = .millisecondsSince1970
        guard let data = try? enc.encode(idx) else { return }
        try? data.write(to: indexURL, options: .atomic)
    }

    // MARK: - Background rebuild

    // Phase-1 shallow walk: stats every jsonl, returns cached entries
    // unchanged and creates stubs for new/changed files using only
    // filesystem metadata. Stubs have nil tokens/title/model — deepScan
    // fills those in later. Returns the entry list plus the set of
    // session ids whose entry needs a deep scan.
    // The on-disk cache stores dates with millisecond precision while
    // file mtimes carry nanoseconds, so an exact == comparison would
    // miss on every entry after a relaunch and re-stub the whole index.
    nonisolated private static func sameTimestamp(_ a: Date, _ b: Date) -> Bool {
        abs(a.timeIntervalSince(b)) < 0.002
    }

    nonisolated private static func rebuildShallow(
        cache: [SessionIndexEntry]
    ) -> (entries: [SessionIndexEntry], stubIds: Set<String>, codexPaths: [String: URL]) {
        let cacheBySessionId: [String: SessionIndexEntry] = Dictionary(
            uniqueKeysWithValues: cache.map { ($0.sessionId, $0) }
        )
        let fm = FileManager.default
        var found: [SessionIndexEntry] = []
        var stubIds: Set<String> = []
        // Rollout file location per Codex stub — deepScan reuses it so
        // it doesn't have to re-enumerate the whole ~/.codex/sessions
        // tree once per stub.
        var codexPaths: [String: URL] = [:]
        let includeTemporary = UserDefaults.standard.bool(forKey: "showTemporarySessions")

        // Claude — ~/.claude/projects/<encoded-cwd>/<sessionId>.jsonl.
        if let projectDirs = try? fm.contentsOfDirectory(at: projectsDir, includingPropertiesForKeys: nil) {
            for projectDir in projectDirs {
                let encodedCwd = projectDir.lastPathComponent
                // Decoding the cwd and classifying it temporary is a pure
                // function of the dir name — memoise it instead of splitting
                // and re-classifying all ~400 names on every 2 s pass.
                let decoded: (cwd: String, isTemp: Bool)
                if let c = cwdDecodeCache[encodedCwd] {
                    decoded = c
                } else {
                    let cwd = "/" + encodedCwd.split(separator: "-").joined(separator: "/")
                    // Drop /private/tmp/* and /private/var/* projects at the
                    // earliest possible step when the user has the toggle
                    // off — saves a stat()+open of every short-lived
                    // sub-task / SDK scratch session.
                    let isTemp = cwd.hasPrefix("/private/tmp/") || cwd.hasPrefix("/private/var/")
                    decoded = (cwd, isTemp)
                    cwdDecodeCache[encodedCwd] = decoded
                }
                if !includeTemporary, decoded.isTemp { continue }
                let cwd = decoded.cwd

                // The jsonl listing only changes when a file is added or
                // removed, which bumps the directory's mtime; reuse the cached
                // listing until then. (In-place appends don't change the dir
                // mtime, but those are caught by the per-file stat below.)
                let dirMtime = (try? fm.attributesOfItem(atPath: projectDir.path))?[.modificationDate] as? Date
                let files: [URL]
                if let cached = dirListCache[encodedCwd], cached.mtime == dirMtime {
                    files = cached.jsonls
                } else {
                    guard let listed = try? fm.contentsOfDirectory(at: projectDir, includingPropertiesForKeys: nil)
                    else { continue }
                    files = listed.filter { $0.pathExtension == "jsonl" }
                    dirListCache[encodedCwd] = (dirMtime ?? .distantPast, files)
                }
                for jsonl in files {
                    let sessionId = jsonl.deletingPathExtension().lastPathComponent
                    guard let attrs = try? fm.attributesOfItem(atPath: jsonl.path),
                          let mtime = attrs[.modificationDate] as? Date,
                          let size = (attrs[.size] as? NSNumber)?.int64Value
                    else { continue }
                    let createdAt = attrs[.creationDate] as? Date
                    let cached = cacheBySessionId[sessionId]

                    if let c = cached,
                       sameTimestamp(c.lastActivity, mtime),
                       c.fileSize == size {
                        // Fully cached — no parse needed at all.
                        found.append(c)
                        continue
                    }
                    if var c = cached, c.fileSize <= size, c.lastParsedSize == c.fileSize {
                        // Partial cache hit: file only grew, and the
                        // cursor is at the previous EOF. Carry totals
                        // over, deepScan will fold the tail bytes only.
                        c.fileSize = size
                        c.lastActivity = mtime
                        found.append(c)
                        stubIds.insert(sessionId)
                        continue
                    }
                    // Fresh / unrecoverable cache → full scan from 0.
                    found.append(SessionIndexEntry(
                        sessionId: sessionId,
                        cwd: cwd,
                        provider: .claude,
                        title: nil, name: nil, model: nil,
                        userMessageCount: 0,
                        lastGitBranch: nil,
                        lastActivity: mtime,
                        startedAt: createdAt,
                        fileSize: size,
                        lastParsedSize: 0
                    ))
                    stubIds.insert(sessionId)
                }
            }
        }

        // Codex — cwd lives inside session_meta, so a fresh stub
        // can only show the sessionId + last activity until deepScan
        // fills the rest.
        if let enumerator = fm.enumerator(at: codexSessionsDir, includingPropertiesForKeys: nil) {
            while let element = enumerator.nextObject() {
                guard let jsonl = element as? URL,
                      jsonl.pathExtension == "jsonl",
                      jsonl.lastPathComponent.hasPrefix("rollout-")
                else { continue }
                guard let attrs = try? fm.attributesOfItem(atPath: jsonl.path),
                      let mtime = attrs[.modificationDate] as? Date,
                      let size = (attrs[.size] as? NSNumber)?.int64Value
                else { continue }
                let basename = jsonl.deletingPathExtension().lastPathComponent
                let sessionId = String(basename.suffix(36))
                guard sessionId.count == 36 else { continue }

                if let cached = cacheBySessionId[sessionId],
                   sameTimestamp(cached.lastActivity, mtime),
                   cached.fileSize == size {
                    found.append(cached)
                    continue
                }
                found.append(SessionIndexEntry(
                    sessionId: sessionId,
                    cwd: "",
                    provider: .codex,
                    title: nil, name: nil, model: nil,
                    userMessageCount: 0,
                    lastGitBranch: nil,
                    lastActivity: mtime,
                    startedAt: nil,
                    fileSize: size
                ))
                stubIds.insert(sessionId)
                codexPaths[sessionId] = jsonl
            }
        }

        // Claude desktop ("local agent mode") — <root>/<account>/<workspace>/
        // local_<uuid>.json metadata beside local_<uuid>/audit.jsonl. We walk
        // exactly two dir levels (not the heavy per-session subtrees), and key
        // freshness off the transcript (the file that grows). The metadata URL
        // is stashed in codexPaths for deepScan to reuse.
        if let accounts = try? fm.contentsOfDirectory(at: claudeDesktopRoot, includingPropertiesForKeys: nil) {
            for account in accounts {
                guard let workspaces = try? fm.contentsOfDirectory(at: account, includingPropertiesForKeys: nil)
                else { continue }
                for ws in workspaces {
                    guard let files = try? fm.contentsOfDirectory(at: ws, includingPropertiesForKeys: nil)
                    else { continue }
                    for meta in files where meta.pathExtension == "json"
                        && meta.lastPathComponent.hasPrefix("local_") {
                        let sessionId = meta.deletingPathExtension().lastPathComponent  // local_<uuid>
                        let audit = meta.deletingPathExtension().appendingPathComponent("audit.jsonl")
                        let heavy = fm.fileExists(atPath: audit.path) ? audit : meta
                        guard let attrs = try? fm.attributesOfItem(atPath: heavy.path),
                              let mtime = attrs[.modificationDate] as? Date,
                              let size = (attrs[.size] as? NSNumber)?.int64Value
                        else { continue }
                        if let cached = cacheBySessionId[sessionId],
                           sameTimestamp(cached.lastActivity, mtime),
                           cached.fileSize == size {
                            found.append(cached)
                            continue
                        }
                        found.append(SessionIndexEntry(
                            sessionId: sessionId,
                            cwd: "",
                            provider: .claudeDesktop,
                            title: nil, name: nil, model: nil,
                            userMessageCount: 0,
                            lastGitBranch: nil,
                            lastActivity: mtime,
                            startedAt: nil,
                            fileSize: size
                        ))
                        stubIds.insert(sessionId)
                        codexPaths[sessionId] = meta
                    }
                }
            }
        }

        found.sort { $0.lastActivity > $1.lastActivity }
        return (found, stubIds, codexPaths)
    }

    // Phase-2 deep scan: locates the jsonl for a stub entry and parses
    // the heavy fields (tokens, title, model, branch, ...). Returns nil
    // if the file disappeared between shallow and deep pass.
    nonisolated private static func deepScan(entry: SessionIndexEntry, fileURL: URL?) -> SessionIndexEntry? {
        switch entry.provider {
        case .claude:
            let jsonl = URL(fileURLWithPath: jsonlPath(for: entry))
            // Seed accumulators with what we already had from cache
            // (zeros if this is a fresh entry).
            // Seed with the previously known cwd / titles so an
            // incremental tail-scan that contains no such records
            // keeps the values instead of resetting them to nil.
            let seed = UsageStats(
                model: entry.model,
                inputTokens: entry.inputTokens,
                cacheCreationTokens: entry.cacheCreationTokens,
                cacheReadTokens: entry.cacheReadTokens,
                outputTokens: entry.outputTokens,
                userMessageCount: entry.userMessageCount,
                turns: entry.turns,
                lastGitBranch: entry.lastGitBranch,
                entrypoint: entry.entrypoint,
                effort: entry.effort,
                cwd: entry.cwd.isEmpty ? nil : entry.cwd,
                aiTitle: entry.title,
                customTitle: entry.name,
                linesAdded: entry.linesAdded,
                linesRemoved: entry.linesRemoved
            )
            guard FileManager.default.fileExists(atPath: jsonl.path) else { return nil }
            let stats = foldUsage(seed: seed, at: jsonl, fromOffset: entry.lastParsedSize)
            var out = entry
            out.title = stats.aiTitle
            out.name = stats.customTitle
            out.model = stats.model
            out.inputTokens = stats.inputTokens
            out.cacheCreationTokens = stats.cacheCreationTokens
            out.cacheReadTokens = stats.cacheReadTokens
            out.outputTokens = stats.outputTokens
            out.userMessageCount = stats.userMessageCount
            out.turns = stats.turns
            out.linesAdded = stats.linesAdded
            out.linesRemoved = stats.linesRemoved
            out.lastGitBranch = stats.lastGitBranch
            out.entrypoint = stats.entrypoint
            out.effort = stats.effort
            if let c = stats.cwd, !c.isEmpty { out.cwd = c }
            out.toolSummary = computeToolSummary(claudeJsonl: jsonl)
            out.lastParsedSize = entry.fileSize
            return out
        case .codex:
            guard let jsonl = fileURL ?? locateCodexJsonl(sessionId: entry.sessionId),
                  let codex = scanCodexSession(at: jsonl)
            else { return nil }
            var out = entry
            out.cwd = codex.cwd ?? entry.cwd
            out.title = codex.title
            out.model = codex.model
            out.effort = codex.effort
            out.inputTokens = codex.inputTokens
            out.cacheCreationTokens = 0
            out.cacheReadTokens = codex.cacheReadTokens
            out.outputTokens = codex.outputTokens
            out.userMessageCount = codex.userMessageCount
            out.turns = codex.turns
            out.startedAt = codex.startedAt
            out.lastParsedSize = entry.fileSize
            return out
        case .claudeDesktop:
            guard let meta = fileURL ?? locateClaudeDesktopMeta(sessionId: entry.sessionId),
                  let d = scanClaudeDesktop(meta: meta)
            else { return nil }
            var out = entry
            if let c = d.cwd, !c.isEmpty { out.cwd = c }
            out.title = d.title
            out.model = d.model
            out.inputTokens = d.inputTokens
            out.cacheCreationTokens = d.cacheCreationTokens
            out.cacheReadTokens = d.cacheReadTokens
            out.outputTokens = d.outputTokens
            out.userMessageCount = d.userMessageCount
            out.turns = d.turns
            out.startedAt = d.startedAt ?? entry.startedAt
            // lastActivity stays the transcript mtime set in the shallow pass,
            // so the next shallow comparison still hits the cache.
            out.lastParsedSize = entry.fileSize
            return out
        }
    }

    // MARK: - Codex scanner

    nonisolated private struct CodexFileStats {
        var cwd: String?
        var title: String?
        var model: String?
        var effort: String?
        var startedAt: Date?
        var inputTokens: Int64 = 0
        var cacheReadTokens: Int64 = 0
        var outputTokens: Int64 = 0
        var userMessageCount: Int = 0
        var turns: Int = 0
    }

    nonisolated private struct CodexSessionMeta: Decodable {
        let cwd: String?
        let timestamp: String?
    }

    nonisolated private struct CodexTurnContext: Decodable {
        let model: String?
        let effort: String?
    }

    nonisolated private struct CodexEventMessage: Decodable {
        let payload: Payload?
        struct Payload: Decodable {
            let type: String?
            // For type == "token_count":
            let info: TokenInfo?
            // For type == "user_message":
            let message: String?
            struct TokenInfo: Decodable {
                let totalTokenUsage: TotalTokenUsage?
                struct TotalTokenUsage: Decodable {
                    let inputTokens: Int64?
                    let cachedInputTokens: Int64?
                    let outputTokens: Int64?
                    let reasoningOutputTokens: Int64?
                }
            }
        }
    }

    nonisolated private static func scanCodexSession(at url: URL) -> CodexFileStats? {
        guard FileManager.default.fileExists(atPath: url.path) else { return nil }
        var stats = CodexFileStats()

        let metaSig = "\"type\":\"session_meta\"".data(using: .utf8)!
        let turnCtxSig = "\"type\":\"turn_context\"".data(using: .utf8)!
        let eventSig = "\"type\":\"event_msg\"".data(using: .utf8)!
        let tokenCountSig = "\"type\":\"token_count\"".data(using: .utf8)!
        let userMsgSig = "\"type\":\"user_message\"".data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let isoParser = ISO8601DateFormatter()
        isoParser.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        var lastTotalUsage: CodexEventMessage.Payload.TokenInfo.TotalTokenUsage?

        _ = JSONLReader.stream(at: url) { lineData in
            if stats.cwd == nil, lineData.range(of: metaSig) != nil {
                // First-line session_meta. payload.cwd is the working
                // directory the codex session was started in;
                // payload.timestamp is when the session began.
                struct MetaRecord: Decodable { let payload: CodexSessionMeta? }
                if let rec = try? decoder.decode(MetaRecord.self, from: lineData) {
                    if let cwd = rec.payload?.cwd { stats.cwd = cwd }
                    if let ts = rec.payload?.timestamp,
                       let d = isoParser.date(from: ts) {
                        stats.startedAt = d
                    }
                }
                return
            }
            if lineData.range(of: turnCtxSig) != nil {
                // turn_context records carry the actual model name
                // (more specific than the gpt-5 default — e.g.
                // "gpt-5.5") and the per-turn reasoning effort knob.
                // The latest one wins.
                struct CtxRecord: Decodable { let payload: CodexTurnContext? }
                if let rec = try? decoder.decode(CtxRecord.self, from: lineData) {
                    if let m = rec.payload?.model {
                        stats.model = "openai-\(m)"
                    }
                    if let e = rec.payload?.effort, !e.isEmpty {
                        stats.effort = e
                    }
                }
                return
            }
            guard lineData.range(of: eventSig) != nil else { return }

            if lineData.range(of: userMsgSig) != nil {
                if let rec = try? decoder.decode(CodexEventMessage.self, from: lineData),
                   let msg = rec.payload?.message {
                    stats.userMessageCount += 1
                    if stats.title == nil {
                        // First user message → take a short prefix
                        // as the displayable title.
                        let trimmed = msg.trimmingCharacters(in: .whitespacesAndNewlines)
                        stats.title = String(trimmed.prefix(80))
                    }
                }
            } else if lineData.range(of: tokenCountSig) != nil {
                // One token_count event per model response → one turn.
                stats.turns += 1
                if let rec = try? decoder.decode(CodexEventMessage.self, from: lineData),
                   let usage = rec.payload?.info?.totalTokenUsage {
                    lastTotalUsage = usage
                }
            }
        }

        // Use cumulative usage from the last token_count event.
        if let u = lastTotalUsage {
            let input = u.inputTokens ?? 0
            let cached = u.cachedInputTokens ?? 0
            // "Fresh" input is what wasn't served from cache.
            stats.inputTokens = max(0, input - cached)
            stats.cacheReadTokens = cached
            stats.outputTokens = (u.outputTokens ?? 0) + (u.reasoningOutputTokens ?? 0)
        }
        // Default to gpt-5 pricing if no turn_context yielded a model.
        if stats.model == nil { stats.model = "openai-gpt-5" }
        return stats
    }

    nonisolated private static func jsonlPath(for entry: SessionIndexEntry) -> String {
        let encoded = entry.cwd.replacingOccurrences(of: "/", with: "-")
        return projectsDir
            .appending(path: encoded, directoryHint: .isDirectory)
            .appending(path: "\(entry.sessionId).jsonl")
            .path
    }

    // MARK: - jsonl parsers

    nonisolated private struct TitleLine: Decodable {
        let aiTitle: String?
        let customTitle: String?
    }

    nonisolated private struct UsageStats {
        var model: String?
        var inputTokens: Int64 = 0
        var cacheCreationTokens: Int64 = 0
        var cacheReadTokens: Int64 = 0
        var outputTokens: Int64 = 0
        var userMessageCount: Int = 0
        var turns: Int = 0
        var lastGitBranch: String?
        var entrypoint: String?
        // Per-session reasoning-effort override set in-session via a command
        // ("Set effort level to X (this session only)"). Claude keeps only a
        // global effortLevel in settings.json, so this is the only signal that
        // a session is running a different effort than the global default.
        var effort: String?
        // Real cwd extracted from any record that carries one — this
        // is the only authoritative source. The encoded directory name
        // under ~/.claude/projects/ is a lossy split-by-dash and breaks
        // on real paths that contain a literal dash (my-project, etc.).
        var cwd: String?
        // ai-title / custom-title records, captured in the same pass
        // as the usage fold (last one wins). Seeded from the cached
        // entry so an incremental tail with no title records keeps
        // the previous values instead of resetting them.
        var aiTitle: String?
        var customTitle: String?
        var linesAdded: Int64 = 0
        var linesRemoved: Int64 = 0
    }

    // Edit / Write tool results: the toolUseResult payload on a user
    // record. "update" carries structuredPatch hunks whose +/- lines
    // are the add/remove counts; "create" carries the new file's
    // content (every line counts as added). Twin of the chart's
    // PatchRecord in TokenChartView — kept separate because the chart
    // also needs the timestamp, decoded with a different strategy.
    nonisolated private struct PatchLine: Decodable {
        let toolUseResult: ToolUseResult?
        struct ToolUseResult: Decodable {
            let type: String?
            let content: String?
            let structuredPatch: [Hunk]?
            struct Hunk: Decodable {
                let lines: [String]?
            }
        }
    }

    nonisolated private struct AssistantRecord: Decodable {
        let message: Message?
        let gitBranch: String?
        let cwd: String?
        // "cli" for a terminal session, "claude-desktop" for the Claude
        // app's Code tab (same ~/.claude storage, different surface).
        let entrypoint: String?
        // Claude Code emits multiple `assistant` records per single
        // API call (one per streamed content block), each carrying the
        // FULL cumulative usage for that call. Summing them naively
        // multiplies real token usage 2-5×. Dedupe by requestId.
        let requestId: String?
        struct Message: Decodable {
            let model: String?
            let usage: Usage?
            struct Usage: Decodable {
                let inputTokens: Int64?
                let outputTokens: Int64?
                let cacheCreationInputTokens: Int64?
                let cacheReadInputTokens: Int64?
            }
        }
    }

    // Walks `data` (the slice of the jsonl starting at byte
    // `startOffset`) and folds it into `seed`. Used both for full
    // scans (seed = zero stats, data = whole file) and for
    // incremental scans (seed = previous totals, data = tail bytes
    // appended since the last index run).
    // Extracts the effort label from a session-only effort command output, e.g.
    //   <local-command-stdout>Set effort level to ultracode (this session only): …
    // Requires the command-stdout wrapper + "(this session only)" so it ignores
    // global-default sets and stray prose, and takes a single token. The anchor
    // is assembled at runtime so this very source doesn't carry the literal it
    // scans for (EpiScope's own transcript would otherwise self-match).
    nonisolated private static func parseSessionEffort(_ s: String) -> String? {
        let anchor = "<local-command-stdout>" + "Set effort level to "
        guard let r = s.range(of: anchor) else { return nil }
        let rest = s[r.upperBound...]
        guard rest.contains("(this session only)") else { return nil }
        let token = rest.prefix { !$0.isWhitespace && $0 != "(" }
        return token.isEmpty ? nil : String(token)
    }

    // Streams the transcript from `offset` and folds the heavy fields without
    // ever holding the whole file in memory.
    nonisolated private static func foldUsage(
        seed: UsageStats,
        at url: URL,
        fromOffset offset: Int64
    ) -> UsageStats {
        var stats = seed

        let assistantSig = "\"type\":\"assistant\"".data(using: .utf8)!
        let userSig = "\"type\":\"user\"".data(using: .utf8)!
        // tool_result records embed a tool_use_id back-reference;
        // typed user prompts don't.
        let toolUseIdSig = "tool_use_id".data(using: .utf8)!
        let titleSig = "-title\"".data(using: .utf8)!  // ai-title + custom-title
        let patchSig = "\"structuredPatch\"".data(using: .utf8)!
        let effortSetSig = "Set effort level to ".data(using: .utf8)!

        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        // Title records carry camelCase keys as-is; decode them with a
        // plain decoder so the snake-case strategy can't interfere.
        let titleDecoder = JSONDecoder()

        // requestId → true once we've counted its tokens. Subsequent
        // records with the same id are streaming repeats and skipped.
        // Reset per fold call — the cost of a single straddled
        // requestId between two runs is one extra count, negligible
        // vs. the I/O savings of incremental parses.
        var countedRequests: Set<String> = []

        _ = JSONLReader.stream(at: url, from: offset) { lineData in
            // Per-session effort override (command output). Latest wins.
            if lineData.range(of: effortSetSig) != nil,
               let s = String(data: lineData, encoding: .utf8),
               let v = Self.parseSessionEffort(s) {
                stats.effort = v
            }
            if lineData.range(of: userSig) != nil {
                if lineData.range(of: toolUseIdSig) == nil {
                    stats.userMessageCount += 1
                } else if lineData.range(of: patchSig) != nil,
                          let patch = try? decoder.decode(PatchLine.self, from: lineData),
                          let result = patch.toolUseResult {
                    switch result.type {
                    case "update":
                        for hunk in result.structuredPatch ?? [] {
                            for l in hunk.lines ?? [] {
                                if l.hasPrefix("+") { stats.linesAdded += 1 }
                                else if l.hasPrefix("-") { stats.linesRemoved += 1 }
                            }
                        }
                    case "create":
                        if let content = result.content, !content.isEmpty {
                            stats.linesAdded += Int64(content.utf8.lazy.filter { $0 == 0x0a }.count) + 1
                        }
                    default:
                        // Read echoes / file_unchanged / bash output
                        // that merely mentions structuredPatch.
                        break
                    }
                }
                return
            }
            if lineData.range(of: assistantSig) == nil {
                // Not user, not assistant — the only other record type
                // we care about is a title. Forward order means the
                // last record seen is the newest, so overwrite.
                if lineData.range(of: titleSig) != nil,
                   let parsed = try? titleDecoder.decode(TitleLine.self, from: lineData) {
                    if let v = parsed.aiTitle { stats.aiTitle = v }
                    if let v = parsed.customTitle { stats.customTitle = v }
                }
                return
            }
            guard let rec = try? decoder.decode(AssistantRecord.self, from: lineData) else { return }
            if let branch = rec.gitBranch, !branch.isEmpty {
                stats.lastGitBranch = branch
            }
            if let e = rec.entrypoint, !e.isEmpty { stats.entrypoint = e }
            if let m = rec.message?.model { stats.model = m }
            if let c = rec.cwd, !c.isEmpty { stats.cwd = c }

            let alreadyCounted: Bool
            if let rid = rec.requestId {
                alreadyCounted = !countedRequests.insert(rid).inserted
            } else {
                alreadyCounted = false
            }
            // Each distinct assistant response (requestId) is one model turn.
            if !alreadyCounted { stats.turns += 1 }
            guard !alreadyCounted, let usage = rec.message?.usage else { return }
            stats.inputTokens += usage.inputTokens ?? 0
            stats.cacheCreationTokens += usage.cacheCreationInputTokens ?? 0
            stats.cacheReadTokens += usage.cacheReadInputTokens ?? 0
            stats.outputTokens += usage.outputTokens ?? 0
        }
        return stats
    }


    // Compact tool-activity summary from a Claude transcript: top tools by call
    // count, top bash verbs, files touched repeatedly. Cached on the entry so
    // reports read it from the index instead of re-parsing the transcript.
    // A full pass (not incremental) — runs only when deepScan sees a change.
    nonisolated private static func computeToolSummary(claudeJsonl url: URL) -> String? {
        struct Rec: Decodable {
            let message: Msg?
            struct Msg: Decodable {
                let content: Content?
                enum Content: Decodable {
                    case blocks([Block]); case ignored
                    init(from d: Decoder) throws {
                        let c = try d.singleValueContainer()
                        self = (try? c.decode([Block].self)).map(Content.blocks) ?? .ignored
                    }
                }
                struct Block: Decodable {
                    let type: String?; let name: String?; let input: Inp?
                    struct Inp: Decodable { let command: String?; let filePath: String? }
                }
            }
        }
        let dec = JSONDecoder()
        dec.keyDecodingStrategy = .convertFromSnakeCase
        var calls: [String: Int] = [:]
        var bash: [String: Int] = [:]
        var files: [String: Int] = [:]
        _ = JSONLReader.stream(at: url) { line in
            guard let r = try? dec.decode(Rec.self, from: line),
                  case let .blocks(bs)? = r.message?.content else { return }
            for b in bs where b.type == "tool_use" {
                guard let n = b.name else { continue }
                calls[n, default: 0] += 1
                if let p = b.input?.filePath {
                    files[URL(fileURLWithPath: p).lastPathComponent, default: 0] += 1
                }
                if n == "Bash", let cmd = b.input?.command,
                   let w = cmd.split(separator: " ").first {
                    bash[String(w), default: 0] += 1
                }
            }
        }
        guard !calls.isEmpty else { return nil }
        var parts = [calls.sorted { $0.value > $1.value }.prefix(4)
            .map { "\($0.key)×\($0.value)" }.joined(separator: ", ")]
        let topBash = bash.sorted { $0.value > $1.value }.prefix(4).map { "\($0.key)×\($0.value)" }
        if !topBash.isEmpty { parts.append("bash: " + topBash.joined(separator: ", ")) }
        let rep = files.filter { $0.value >= 3 }.sorted { $0.value > $1.value }.prefix(3)
            .map { "\($0.key)×\($0.value)" }
        if !rep.isEmpty { parts.append("files: " + rep.joined(separator: ", ")) }
        return parts.joined(separator: " · ")
    }

    // MARK: - Claude desktop ("local agent mode") scanner

    nonisolated private struct DesktopStats {
        var cwd: String?
        var title: String?
        var model: String?
        var inputTokens: Int64 = 0
        var cacheCreationTokens: Int64 = 0
        var cacheReadTokens: Int64 = 0
        var outputTokens: Int64 = 0
        var userMessageCount: Int = 0
        var turns: Int = 0
        var startedAt: Date?
    }

    // One audit.jsonl record. Explicit snake_case keys (no global
    // convertFromSnakeCase) so "_audit_timestamp" / "request_id" decode and
    // the ubiquitous "parent_tool_use_id" can't be mistaken for a tool result.
    nonisolated private struct AuditRec: Decodable {
        let type: String?
        let auditTimestamp: String?
        let requestId: String?
        let message: Msg?
        enum CodingKeys: String, CodingKey {
            case type
            case auditTimestamp = "_audit_timestamp"
            case requestId = "request_id"
            case message
        }
        struct Msg: Decodable {
            let role: String?
            let model: String?
            let content: Content?
            let usage: Usage?
            enum Content: Decodable {
                case text(String)
                case blocks([Block])
                init(from decoder: Decoder) throws {
                    let c = try decoder.singleValueContainer()
                    if let s = try? c.decode(String.self) { self = .text(s); return }
                    self = .blocks((try? c.decode([Block].self)) ?? [])
                }
            }
            struct Block: Decodable { let type: String?; let text: String? }
            struct Usage: Decodable {
                let inputTokens: Int64?
                let cacheCreationInputTokens: Int64?
                let cacheReadInputTokens: Int64?
                let outputTokens: Int64?
                enum CodingKeys: String, CodingKey {
                    case inputTokens = "input_tokens"
                    case cacheCreationInputTokens = "cache_creation_input_tokens"
                    case cacheReadInputTokens = "cache_read_input_tokens"
                    case outputTokens = "output_tokens"
                }
            }
        }
    }

    // Metadata (title / real folder / created) + token usage folded from the
    // sibling audit.jsonl. No structuredPatch in the audit, so line churn is
    // left at 0 (like Codex).
    nonisolated private static func scanClaudeDesktop(meta metaURL: URL) -> DesktopStats? {
        var stats = DesktopStats()
        if let mdata = try? Data(contentsOf: metaURL),
           let obj = (try? JSONSerialization.jsonObject(with: mdata)) as? [String: Any] {
            stats.title = (obj["title"] as? String).flatMap { $0.isEmpty ? nil : $0 }
            stats.cwd = (obj["userSelectedFolders"] as? [String])?.first ?? (obj["cwd"] as? String)
            if let created = obj["createdAt"] as? Double {
                stats.startedAt = Date(timeIntervalSince1970: created / 1000)
            }
        }
        let audit = metaURL.deletingPathExtension().appendingPathComponent("audit.jsonl")
        let decoder = JSONDecoder()
        var counted = Set<String>()
        _ = JSONLReader.stream(at: audit) { line in
            guard let rec = try? decoder.decode(AuditRec.self, from: line) else { return }
            switch rec.type {
            case "user":
                if case .text(let s)? = rec.message?.content,
                   !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    stats.userMessageCount += 1
                }
            case "assistant":
                if let rid = rec.requestId, !counted.insert(rid).inserted { return }
                stats.turns += 1
                if let m = rec.message?.model, !m.isEmpty { stats.model = m }
                if let u = rec.message?.usage {
                    stats.inputTokens += u.inputTokens ?? 0
                    stats.cacheCreationTokens += u.cacheCreationInputTokens ?? 0
                    stats.cacheReadTokens += u.cacheReadInputTokens ?? 0
                    stats.outputTokens += u.outputTokens ?? 0
                }
            default:
                break
            }
        }
        return stats
    }

    nonisolated private static func locateClaudeDesktopMeta(sessionId: String) -> URL? {
        let fm = FileManager.default
        guard let accounts = try? fm.contentsOfDirectory(at: claudeDesktopRoot, includingPropertiesForKeys: nil)
        else { return nil }
        for account in accounts {
            guard let workspaces = try? fm.contentsOfDirectory(at: account, includingPropertiesForKeys: nil)
            else { continue }
            for ws in workspaces {
                let candidate = ws.appendingPathComponent("\(sessionId).json")
                if fm.fileExists(atPath: candidate.path) { return candidate }
            }
        }
        return nil
    }

    nonisolated private static func loadClaudeDesktopTranscript(from data: Data) -> [TranscriptEvent] {
        let decoder = JSONDecoder()
        let isoF = ISO8601DateFormatter(); isoF.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        let isoP = ISO8601DateFormatter(); isoP.formatOptions = [.withInternetDateTime]
        func parse(_ s: String?) -> Date? { s.flatMap { isoF.date(from: $0) ?? isoP.date(from: $0) } }

        var events: [TranscriptEvent] = []
        var cumIn: Int64 = 0, cumCache: Int64 = 0, cumOut: Int64 = 0
        var counted = Set<String>()
        for line in data.split(separator: 0x0a, omittingEmptySubsequences: true) {
            guard let rec = try? decoder.decode(AuditRec.self, from: Data(line)) else { continue }
            let ts = parse(rec.auditTimestamp)
            switch rec.type {
            case "user":
                if case .text(let s)? = rec.message?.content {
                    let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
                    guard !trimmed.isEmpty else { continue }
                    events.append(TranscriptEvent(kind: .user, timestamp: ts, text: trimmed,
                                                  cumInput: nil, cumCacheRead: nil, cumOutput: nil))
                }
            case "assistant":
                let fresh = rec.requestId.map { counted.insert($0).inserted } ?? true
                if fresh, let u = rec.message?.usage {
                    cumIn += u.inputTokens ?? 0
                    cumCache += u.cacheReadInputTokens ?? 0
                    cumOut += u.outputTokens ?? 0
                }
                var text = ""
                if case .blocks(let blocks)? = rec.message?.content {
                    text = blocks.compactMap { $0.type == "text" ? $0.text : nil }.joined(separator: "\n")
                } else if case .text(let s)? = rec.message?.content {
                    text = s
                }
                events.append(TranscriptEvent(kind: .assistant, timestamp: ts,
                                              text: text.trimmingCharacters(in: .whitespacesAndNewlines),
                                              cumInput: cumIn, cumCacheRead: cumCache, cumOutput: cumOut))
            default:
                break
            }
        }
        return events
    }

    // MARK: - Transcript loader

    nonisolated struct TranscriptEvent: Sendable {
        enum Kind: Sendable { case user, assistant }
        let kind: Kind
        let timestamp: Date?
        let text: String
        // Cumulative tokens at this point in the session (or nil if
        // the event itself carries no usage data).
        let cumInput: Int64?
        let cumCacheRead: Int64?
        let cumOutput: Int64?
    }

    // On-disk transcript file for a session (the jsonl for Claude / Codex,
    // the audit.jsonl for a Cowork desktop session). nil if it can't be
    // located. Used by loadTranscript and the row's "Reveal in Finder".
    nonisolated static func transcriptURL(for entry: SessionIndexEntry) -> URL? {
        switch entry.provider {
        case .claude:
            return URL(fileURLWithPath: jsonlPath(for: entry))
        case .codex:
            return locateCodexJsonl(sessionId: entry.sessionId)
        case .claudeDesktop:
            guard let meta = locateClaudeDesktopMeta(sessionId: entry.sessionId) else { return nil }
            return meta.deletingPathExtension().appendingPathComponent("audit.jsonl")
        }
    }

    // Same as above but from primitives, so the search indexer can locate a
    // transcript off the main actor (the Codex/Desktop cases walk the session
    // tree) without building a full entry. cwd is only used for Claude.
    nonisolated static func transcriptURL(provider: SessionProvider,
                                          sessionId: String, cwd: String) -> URL? {
        switch provider {
        case .claude:
            let encoded = cwd.replacingOccurrences(of: "/", with: "-")
            return projectsDir
                .appending(path: encoded, directoryHint: .isDirectory)
                .appending(path: "\(sessionId).jsonl")
        case .codex:
            return locateCodexJsonl(sessionId: sessionId)
        case .claudeDesktop:
            guard let meta = locateClaudeDesktopMeta(sessionId: sessionId) else { return nil }
            return meta.deletingPathExtension().appendingPathComponent("audit.jsonl")
        }
    }

    // Sessions can run to tens of MB; rendering the whole thing into one
    // NSAttributedString + TextKit layout is what spiked memory to hundreds of
    // MB. Load only the tail (recent messages) of a large transcript — that's
    // what the viewer actually shows — and report whether we truncated.
    nonisolated static let transcriptTailBytes = 4_000_000
    nonisolated static func loadTranscript(for entry: SessionIndexEntry)
        -> (events: [TranscriptEvent], truncated: Bool) {
        guard let url = transcriptURL(for: entry) else { return ([], false) }
        let (data, truncated) = tailData(of: url, maxBytes: transcriptTailBytes)
        let events: [TranscriptEvent]
        switch entry.provider {
        case .claude:        events = loadClaudeTranscript(from: data)
        case .codex:         events = loadCodexTranscript(from: data)
        case .claudeDesktop: events = loadClaudeDesktopTranscript(from: data)
        }
        return (events, truncated)
    }

    // Whole file if it's within maxBytes, otherwise the last maxBytes starting
    // at the next line boundary (so parsing begins on a clean record).
    nonisolated private static func tailData(of url: URL, maxBytes: Int) -> (Data, truncated: Bool) {
        let fm = FileManager.default
        let size = (try? fm.attributesOfItem(atPath: url.path))?[.size] as? Int ?? 0
        guard size > maxBytes, let handle = try? FileHandle(forReadingFrom: url) else {
            return ((try? Data(contentsOf: url)) ?? Data(), false)
        }
        defer { try? handle.close() }
        try? handle.seek(toOffset: UInt64(size - maxBytes))
        var data = (try? handle.readToEnd()) ?? Data()
        if let nl = data.firstIndex(of: 0x0a) {
            data = Data(data[data.index(after: nl)...])
        }
        return (data, true)
    }

    nonisolated private static func locateCodexJsonl(sessionId: String) -> URL? {
        let fm = FileManager.default
        guard let enumerator = fm.enumerator(at: codexSessionsDir, includingPropertiesForKeys: nil)
        else { return nil }
        while let element = enumerator.nextObject() as? URL {
            guard element.pathExtension == "jsonl",
                  element.lastPathComponent.hasPrefix("rollout-"),
                  element.lastPathComponent.contains(sessionId)
            else { continue }
            return element
        }
        return nil
    }

    nonisolated private struct ClaudeTranscriptRecord: Decodable {
        let type: String?
        let timestamp: String?
        let message: Msg?
        struct Msg: Decodable {
            let role: String?
            let content: Content?
            let usage: Usage?
            enum Content: Decodable {
                case text(String)
                case blocks([Block])
                init(from decoder: Decoder) throws {
                    let c = try decoder.singleValueContainer()
                    if let s = try? c.decode(String.self) { self = .text(s); return }
                    self = .blocks((try? c.decode([Block].self)) ?? [])
                }
            }
            struct Block: Decodable {
                let type: String?
                let text: String?
            }
            struct Usage: Decodable {
                let inputTokens: Int64?
                let cacheCreationInputTokens: Int64?
                let cacheReadInputTokens: Int64?
                let outputTokens: Int64?
            }
        }
    }

    nonisolated private static func loadClaudeTranscript(from data: Data) -> [TranscriptEvent] {
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let isoParser = ISO8601DateFormatter()
        isoParser.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        var events: [TranscriptEvent] = []
        var cumIn: Int64 = 0
        var cumCache: Int64 = 0
        var cumOut: Int64 = 0

        for line in data.split(separator: 0x0a, omittingEmptySubsequences: true) {
            let lineData = Data(line)
            guard let rec = try? decoder.decode(ClaudeTranscriptRecord.self, from: lineData) else { continue }
            let ts = rec.timestamp.flatMap { isoParser.date(from: $0) }
            switch rec.type {
            case "user":
                // Plain typed user message: content is a string.
                // Tool result echoes: content is an array of tool_result
                // blocks, no user text — skip those.
                if case let .text(s) = rec.message?.content {
                    let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
                    guard !trimmed.isEmpty else { continue }
                    events.append(TranscriptEvent(
                        kind: .user, timestamp: ts, text: trimmed,
                        cumInput: nil, cumCacheRead: nil, cumOutput: nil
                    ))
                }
            case "assistant":
                if let usage = rec.message?.usage {
                    cumIn += usage.inputTokens ?? 0
                    cumCache += usage.cacheReadInputTokens ?? 0
                    cumOut += usage.outputTokens ?? 0
                }
                // Pull text out of "text" content blocks only;
                // skip tool_use / thinking blocks per the user request.
                if case let .blocks(blocks) = rec.message?.content {
                    let text = blocks
                        .filter { $0.type == "text" }
                        .compactMap { $0.text?.trimmingCharacters(in: .whitespacesAndNewlines) }
                        .filter { !$0.isEmpty }
                        .joined(separator: "\n\n")
                    if !text.isEmpty {
                        events.append(TranscriptEvent(
                            kind: .assistant, timestamp: ts, text: text,
                            cumInput: cumIn, cumCacheRead: cumCache, cumOutput: cumOut
                        ))
                    }
                }
            default: break
            }
        }
        return events
    }

    nonisolated private struct CodexTranscriptRecord: Decodable {
        let type: String?
        let timestamp: String?
        let payload: Payload?
        struct Payload: Decodable {
            let type: String?
            let message: String?
            let info: TokenInfo?
            struct TokenInfo: Decodable {
                let totalTokenUsage: Total?
                struct Total: Decodable {
                    let inputTokens: Int64?
                    let cachedInputTokens: Int64?
                    let outputTokens: Int64?
                    let reasoningOutputTokens: Int64?
                }
            }
        }
    }

    nonisolated private static func loadCodexTranscript(from data: Data) -> [TranscriptEvent] {
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let isoParser = ISO8601DateFormatter()
        isoParser.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        var events: [TranscriptEvent] = []
        var cumIn: Int64 = 0
        var cumCache: Int64 = 0
        var cumOut: Int64 = 0

        for line in data.split(separator: 0x0a, omittingEmptySubsequences: true) {
            let lineData = Data(line)
            guard let rec = try? decoder.decode(CodexTranscriptRecord.self, from: lineData),
                  rec.type == "event_msg",
                  let pt = rec.payload?.type
            else { continue }
            let ts = rec.timestamp.flatMap { isoParser.date(from: $0) }
            switch pt {
            case "token_count":
                if let u = rec.payload?.info?.totalTokenUsage {
                    let totalIn = u.inputTokens ?? 0
                    let cached = u.cachedInputTokens ?? 0
                    cumIn = max(0, totalIn - cached)
                    cumCache = cached
                    cumOut = (u.outputTokens ?? 0) + (u.reasoningOutputTokens ?? 0)
                }
            case "user_message":
                if let m = rec.payload?.message?.trimmingCharacters(in: .whitespacesAndNewlines),
                   !m.isEmpty {
                    events.append(TranscriptEvent(
                        kind: .user, timestamp: ts, text: m,
                        cumInput: nil, cumCacheRead: nil, cumOutput: nil
                    ))
                }
            case "agent_message":
                if let m = rec.payload?.message?.trimmingCharacters(in: .whitespacesAndNewlines),
                   !m.isEmpty {
                    events.append(TranscriptEvent(
                        kind: .assistant, timestamp: ts, text: m,
                        cumInput: cumIn, cumCacheRead: cumCache, cumOutput: cumOut
                    ))
                }
            default: break
            }
        }
        return events
    }

    // MARK: - Search indexing support

    // Streams the human + assistant text of a transcript from `offset`, one
    // call to `body` per message, without ever holding the whole file in
    // memory. Mirrors the transcript viewer's extraction (typed user prompts +
    // assistant "text" blocks; Codex user/agent messages; desktop audit
    // user/assistant) but incrementally, so the FTS indexer folds only the
    // appended tail of a growing transcript. Returns the absolute byte offset
    // past the last complete line parsed — the caller stores it as its cursor.
    nonisolated static func indexableMessages(
        provider: SessionProvider,
        at url: URL,
        fromOffset offset: Int64,
        _ body: (_ role: String, _ timestamp: Date?, _ text: String) -> Void
    ) -> Int64 {
        switch provider {
        case .claude:
            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase
            let iso = ISO8601DateFormatter()
            iso.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
            return JSONLReader.stream(at: url, from: offset) { line in
                guard let rec = try? decoder.decode(ClaudeTranscriptRecord.self, from: line) else { return }
                let ts = rec.timestamp.flatMap { iso.date(from: $0) }
                switch rec.type {
                case "user":
                    if case let .text(s) = rec.message?.content {
                        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
                        if !t.isEmpty { body("user", ts, t) }
                    }
                case "assistant":
                    if case let .blocks(blocks) = rec.message?.content {
                        let t = blocks
                            .filter { $0.type == "text" }
                            .compactMap { $0.text?.trimmingCharacters(in: .whitespacesAndNewlines) }
                            .filter { !$0.isEmpty }
                            .joined(separator: "\n\n")
                        if !t.isEmpty { body("assistant", ts, t) }
                    }
                default: break
                }
            }
        case .codex:
            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase
            let iso = ISO8601DateFormatter()
            iso.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
            return JSONLReader.stream(at: url, from: offset) { line in
                guard let rec = try? decoder.decode(CodexTranscriptRecord.self, from: line),
                      rec.type == "event_msg", let pt = rec.payload?.type else { return }
                let ts = rec.timestamp.flatMap { iso.date(from: $0) }
                switch pt {
                case "user_message":
                    if let m = rec.payload?.message?.trimmingCharacters(in: .whitespacesAndNewlines),
                       !m.isEmpty { body("user", ts, m) }
                case "agent_message":
                    if let m = rec.payload?.message?.trimmingCharacters(in: .whitespacesAndNewlines),
                       !m.isEmpty { body("assistant", ts, m) }
                default: break
                }
            }
        case .claudeDesktop:
            let decoder = JSONDecoder()
            let iso = ISO8601DateFormatter(); iso.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
            let isoNoFrac = ISO8601DateFormatter(); isoNoFrac.formatOptions = [.withInternetDateTime]
            return JSONLReader.stream(at: url, from: offset) { line in
                guard let rec = try? decoder.decode(AuditRec.self, from: line) else { return }
                let ts = rec.auditTimestamp.flatMap { iso.date(from: $0) ?? isoNoFrac.date(from: $0) }
                switch rec.type {
                case "user":
                    if case .text(let s)? = rec.message?.content {
                        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
                        if !t.isEmpty { body("user", ts, t) }
                    }
                case "assistant":
                    var text = ""
                    if case .blocks(let blocks)? = rec.message?.content {
                        text = blocks.compactMap { $0.type == "text" ? $0.text : nil }.joined(separator: "\n")
                    } else if case .text(let s)? = rec.message?.content {
                        text = s
                    }
                    let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
                    if !t.isEmpty { body("assistant", ts, t) }
                default: break
                }
            }
        }
    }
}
